### ISSUE TITLE
issue installing escape_utils -v '0.3.2'

### ISSUE THREAD

**Issue by hiromipaw** [brianmario/escape_utils#57]
Hello,
I have been trying to install escape_utils -v '0.3.2' and I get the following error:

$ gem install escape_utils  -v '0.3.2'
Building native extensions.  This could take a while...
ERROR: Error installing escape_utils:
ERROR: Failed to build gem native extension.

/Users/<user>/.rvm/rubies/ruby-2.1.0/bin/ruby extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling buffer.c
compiling escape_utils.c
escape_utils.c:126:24: error: read-only variable is not assignable
RBASIC(result)->klass = rb_html_safe_string_class;

1 error generated.
make: **\* [escape_utils.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/<user>/.rvm/gems/ruby-2.1.0/gems/escape_utils-0.3.2 for inspection.
Results logged to /Users/<user>/.rvm/gems/ruby-2.1.0/extensions/x86_64-darwin-12/2.1.0-static/escape_utils-0.3.2/gem_make.out

My ruby version is the following:
$ ruby -v
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin12.0]

I am also able to do gem install escape_utils and work with version 1.0.0 without any problems.

Any help would be appreciated.

Cheers!
